### ISSUE TITLE
Bug: The mouse cursor does not adapt its shape on hovering the image in the darkroom

### ISSUE THREAD

**Issue by sahlirc** [aurelienpierreeng/ansel#660]
### Code of Conduct

- [x] I have read this document and I accept the conditions

### Search previous report

- [x] I have searched my issue

### Computer's operating system

Linux

### What GPU do you have ?

Nvidia

### Ansel version

2845

### Type of binary

Pre-built packages provided by the Ansel project (.AppImage, .EXE)

### What happened?

The mouse cursor should change its shape when hovering the image in the darkroom, reflecting its underlying job. It is as if the image itself is not detected from the background of the darkroom, hence one could expect that the job itself may not be undertaken (the action of the mouse wheel on zooming in/out is however preserved).

### Does your problem occur with OpenCL enabled ?

Yes

### Does your problem occur with OpenCL disabled ?

I don't know

### Previous Ansel version that use to work

2686.

### Output of ansel -d all

```shell

```

### Backtrace

```shell

```

**Comment by sahlirc** [comment]
Please note that bisection from 2686 upwards is nearly impossible to perform as versions cannot be compiled with fatal errors such as this one:
/home/roland/ansel/src/iop/colorin.c: In function ‘process_lcms2_bm’:
/home/roland/ansel/src/iop/colorin.c:989:45: error: invalid increment expression
  989 |       for(int j = 0; j < roi_out->width; j++, rgbptr += 4)
      |                                             ^
compilation terminated due to -Wfatal-errors.
the first commit that shows this is 0b868de040bef30c948f07bf4af6245879d3540a

Since version 2831 seems not to be fraught with this cursor bug, I could bisect from this version up to 2845 and identified 454987b84035ac56a4b50fa015e5e430f909d043 as the most recent bad commit.

**Comment by Jiyone** [comment]
haha no there is no relation between this and the pipette.
