### ISSUE TITLE
Bug: Ansel build failure Ubuntu 22.04 with GCC 12

### ISSUE THREAD

**Issue by Markfas** [aurelienpierreeng/ansel#784]
### Issue is actionnable and focused on a single problem

- [x] My issue is not a question but ONE identified usability problem.

### Search previous report

- [x] I have searched my issue

### Computer's operating system

Linux

### What GPU do you have ?

Nvidia

### Ansel version

364cab77b

### Type of binary

Self-compiled (GCC or Clang)

### What happened?

Building process stopped with error:

 `<command-line>: error: macro names must be identifiers`

see attached txt-file

[build-failure#784.txt](https://github.com/user-attachments/files/26903043/build-failure.784.txt)

### Does your problem occur with OpenCL enabled ?

No

### Does your problem occur with OpenCL disabled ?

No

### Output of ansel -d all

```shell

```

### Backtrace

```shell

```

**Comment by Markfas** [comment]
Last working version is `4ccef4d`
Commit `cffd508` broke the compilation.

**Comment by aurelienpierre** [comment]
On what file/lines does the compiler break ? And what compiler is that by the way ?

**Comment by Markfas** [comment]
Build generator:     Ninja
Compiler:            gcc g++

First error occurs in line 41, affected file is src/CMakeFi...o_libraw.dir/common/imageio_libraw.c.o
see output:

```
[0/2] Re-checking globbed directories...
[1/930] Updating version string (git checkout)
fatal: No tags can describe '5b2bc3662b220f1b0218c36f45a9535c8e0659e4'.
Try --always, or create some tags.
Version string: 5b2bc3662
[2/930] Generating src/version_gen.c

[3/930] Building ca locale
1823 translated messages, 878 fuzzy translations, 1291 untranslated messages.
[4/930] Building af locale
2817 translated messages, 484 fuzzy translations, 691 untranslated messages.
[5/930] Building cs locale
3325 translated messages, 286 fuzzy translations, 381 untranslated messages.
[6/930] Building da locale
1820 translated messages, 880 fuzzy translations, 1292 untranslated messages.
[7/930] Building el locale
1173 translated messages, 1021 fuzzy translations, 1798 untranslated messages.
[8/930] Building de locale
3917 translated messages, 33 fuzzy translations, 42 untranslated messages.
[9/930] Building eo locale
3325 translated messages, 286 fuzzy translations, 381 untranslated messages.
[10/930] Building es locale
3751 translated messages, 140 fuzzy translations, 101 untranslated messages.
[11/930] Building fi locale
3295 translated messages, 289 fuzzy translations, 408 untranslated messages.
[12/930] Building gl locale
216 translated messages, 649 fuzzy translations, 3127 untranslated messages.
[13/930] Building fr locale
3838 translated messages, 58 fuzzy translations, 96 untranslated messages.
[14/930] Building he locale
3294 translated messages, 290 fuzzy translations, 408 untranslated messages.
[15/930] Building hu locale
3362 translated messages, 271 fuzzy translations, 359 untranslated messages.
[16/930] Building ja locale
3295 translated messages, 289 fuzzy translations, 408 untranslated messages.
[17/930] Building it locale
3917 translated messages, 33 fuzzy translations, 42 untranslated messages.
[18/930] Building nb locale
1818 translated messages, 880 fuzzy translations, 1294 untranslated messages.
[19/930] Building nl locale
3297 translated messages, 289 fuzzy translations, 406 untranslated messages.
[20/930] Building pl locale
3295 translated messages, 289 fuzzy translations, 408 untranslated messages.
[21/930] Building pt_BR locale
3296 translated messages, 288 fuzzy translations, 408 untranslated messages.
[22/930] Building pt_PT locale
932 translated messages, 1006 fuzzy translations, 2054 untranslated messages.
[23/930] Building ro locale
417 translated messages, 845 fuzzy translations, 2730 untranslated messages.
[24/930] Building ru locale
3296 translated messages, 288 fuzzy translations, 408 untranslated messages.
[25/930] Building sk locale
2464 translated messages, 677 fuzzy translations, 851 untranslated messages.
[26/930] Building sl locale
3295 translated messages, 289 fuzzy translations, 408 untranslated messages.
[27/930] Building sq locale
3207 translated messages, 346 fuzzy translations, 439 untranslated messages.
[28/930] Building sr locale
2579 translated messages, 637 fuzzy translations, 776 untranslated messages.
[29/930] Building sr@latin locale
2579 translated messages, 637 fuzzy translations, 776 untranslated messages.
[30/930] Building sv locale
2035 translated messages, 874 fuzzy translations, 1083 untranslated messages.
[31/930] Building th locale
248 translated messages, 624 fuzzy translations, 3120 untranslated messages.
[32/930] Building tr locale
3295 translated messages, 289 fuzzy translations, 408 untranslated messages.
[33/930] Building zh_CN locale
3991 translated messages, 1 fuzzy translation.
[34/930] Building uk locale
3295 translated messages, 289 fuzzy translations, 408 untranslated messages.
[35/930] Building zh_TW locale
3289 translated messages, 294 fuzzy translations, 409 untranslated messages.
[41/930] Building C object src/CMakeFi...o_libraw.dir/common/imageio_libraw.c.o
FAILED: src/CMakeFiles/lib_ansel_imageio_libraw.dir/common/imageio_libraw.c.o 
/usr/bin/gcc -D-DLIBSOUP_VERSION_MAJOR=2 -DAVIF_DLL -DGDK_DISABLE_DEPRECATED -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_24 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_MIN_REQUIRED -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_64 -DGTK_DISABLE_DEPRECATED -DGTK_DISABLE_SINGLE_INCLUDES -DHAVE_CMARK=1 -DHAVE_CONFIG_H=1 -DHAVE_GMIC=1 -DHAVE_GRAPHICSMAGICK=1 -DHAVE_HTTP_SERVER=1 -DHAVE_ISO_CODES=1 -DHAVE_KWALLET=1 -DHAVE_LIBAVIF=1 -DHAVE_LIBEXIV2_WITH_ISOBMFF=1 -DHAVE_LIBRAW=1 -DHAVE_LIBSECRET=1 -DHAVE_MAP=1 -DHAVE_OPENCL=1 -DHAVE_OPENEXR=1 -DHAVE_OPENJPEG=1 -DHAVE_OSMGPSMAP_110_OR_NEWER=1 -DHAVE_OSMGPSMAP_NEWER_THAN_110=1 -DHAVE_PRINT=1 -DHAVE_WEBP=1 -DLIBRAW_NODLL -DLIBSOUP_VERSION_MAJOR=2 -DNATIVE_ARCH -DUSE_COLORDGTK -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200809L -D__GDK_KEYSYMS_COMPAT_H__ -I/home/Source/ansel/build/src -I/home/Source/ansel/src -I/home/Source/ansel/src/external/LibRaw -I/home/Source/ansel/src/LCMS2::LCMS2 -I/home/Source/ansel/src/PNG::PNG -I/home/Source/ansel/src/JPEG::JPEG -I/home/Source/ansel/src/TIFF::TIFF -I/home/Source/ansel/src/LensFun::LensFun -I/home/Source/ansel/src/Sqlite3::Sqlite3 -I/home/Source/ansel/src/Exiv2::Exiv2 -I/home/Source/ansel/src/Pugixml::Pugixml -I/home/Source/ansel/src/CURL::libcurl -isystem /home/Source/ansel/src/external -isystem /home/Source/ansel/src/external/OpenCL -isystem /usr/include/gtk-3.0 -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/harfbuzz -isystem /usr/include/fribidi -isystem /usr/include/atk-1.0 -isystem /usr/include/pixman-1 -isystem /usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libpng16 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/librsvg-2.0 -isystem /usr/include/json-glib-1.0 -isystem /usr/include/libxml2 -isystem /usr/include/lensfun -isystem /usr/include/libsoup-2.4 -isystem /usr/include/OpenEXR -isystem /usr/include/openjpeg-2.4 -isystem /usr/include/libsecret-1 -isystem /usr/include/GraphicsMagick -isystem /usr/include/osmgpsmap-1.0 -isystem /usr/include/colord-1 -march=native -mtune=native -Wall -funroll-loops -ftree-vectorize -fno-strict-aliasing -Wmaybe-uninitialized -Wno-undef -Wimplicit-function-declaration -Winfinite-recursion -fno-semantic-interposition -fno-signaling-nans -floop-nest-optimize -ftree-loop-im -fvariable-expansion-in-unroller -ftree-loop-im -fira-loop-pressure  -fopenmp -O3 -DNDEBUG -ffast-math -ffp-contract=fast -fno-finite-math-only -Wall -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wno-unknown-pragmas -Wno-error=varargs -Wno-format-truncation -Wno-error=address-of-packed-member -O3 -DNDEBUG -ffast-math -ffp-contract=fast -fno-finite-math-only -flto -fno-fat-lto-objects -fPIC -fdiagnostics-color=always -pthread -std=c11 -MD -MT src/CMakeFiles/lib_ansel_imageio_libraw.dir/common/imageio_libraw.c.o -MF src/CMakeFiles/lib_ansel_imageio_libraw.dir/common/imageio_libraw.c.o.d -o src/CMakeFiles/lib_ansel_imageio_libraw.dir/common/imageio_libraw.c.o -c /home/Source/ansel/src/common/imageio_libraw.c
<command-line>: error: macro names must be identifiers
[42/930] Building C object src/CMakeFiles/help_menu.dir/gui/actions/help.c.o
FAILED: src/CMakeFiles/help_menu.dir/gui/actions/help.c.o 
/usr/bin/gcc -D-DLIBSOUP_VERSION_MAJOR=2 -DAVIF_DLL -DGDK_DISABLE_DEPRECATED -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_24 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_MIN_REQUIRED -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_64 -DGTK_DISABLE_DEPRECATED -DGTK_DISABLE_SINGLE_INCLUDES -DHAVE_CMARK=1 -DHAVE_CONFIG_H=1 -DHAVE_GMIC=1 -DHAVE_GRAPHICSMAGICK=1 -DHAVE_HTTP_SERVER=1 -DHAVE_ISO_CODES=1 -DHAVE_KWALLET=1 -DHAVE_LIBAVIF=1 -DHAVE_LIBEXIV2_WITH_ISOBMFF=1 -DHAVE_LIBRAW=1 -DHAVE_LIBSECRET=1 -DHAVE_MAP=1 -DHAVE_OPENCL=1 -DHAVE_OPENEXR=1 -DHAVE_OPENJPEG=1 -DHAVE_OSMGPSMAP_110_OR_NEWER=1 -DHAVE_OSMGPSMAP_NEWER_THAN_110=1 -DHAVE_PRINT=1 -DHAVE_WEBP=1 -DLIBSOUP_VERSION_MAJOR=2 -DNATIVE_ARCH -DUSE_COLORDGTK -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200809L -D__GDK_KEYSYMS_COMPAT_H__ -I/home/Source/ansel/build/src -I/home/Source/ansel/src -I/home/Source/ansel/src/LCMS2::LCMS2 -I/home/Source/ansel/src/PNG::PNG -I/home/Source/ansel/src/JPEG::JPEG -I/home/Source/ansel/src/TIFF::TIFF -I/home/Source/ansel/src/LensFun::LensFun -I/home/Source/ansel/src/Sqlite3::Sqlite3 -I/home/Source/ansel/src/Exiv2::Exiv2 -I/home/Source/ansel/src/Pugixml::Pugixml -I/home/Source/ansel/src/CURL::libcurl -isystem /home/Source/ansel/src/external -isystem /home/Source/ansel/src/external/OpenCL -isystem /usr/include/gtk-3.0 -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/harfbuzz -isystem /usr/include/fribidi -isystem /usr/include/atk-1.0 -isystem /usr/include/pixman-1 -isystem /usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libpng16 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/librsvg-2.0 -isystem /usr/include/json-glib-1.0 -isystem /usr/include/libxml2 -isystem /usr/include/lensfun -isystem /usr/include/libsoup-2.4 -isystem /usr/include/OpenEXR -isystem /usr/include/openjpeg-2.4 -isystem /usr/include/libsecret-1 -isystem /usr/include/GraphicsMagick -isystem /usr/include/osmgpsmap-1.0 -isystem /usr/include/colord-1 -march=native -mtune=native -Wall -funroll-loops -ftree-vectorize -fno-strict-aliasing -Wmaybe-uninitialized -Wno-undef -Wimplicit-function-declaration -Winfinite-recursion -fno-semantic-interposition -fno-signaling-nans -floop-nest-optimize -ftree-loop-im -fvariable-expansion-in-unroller -ftree-loop-im -fira-loop-pressure  -fopenmp -O3 -DNDEBUG -ffast-math -ffp-contract=fast -fno-finite-math-only -Wall -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wno-unknown-pragmas -Wno-error=varargs -Wno-format-truncation -Wno-error=address-of-packed-member -O3 -DNDEBUG -ffast-math -ffp-contract=fast -fno-finite-math-only -flto -fno-fat-lto-objects -fPIC -fdiagnostics-color=always -pthread -std=c11 -MD -MT src/CMakeFiles/help_menu.dir/gui/actions/help.c.o -MF src/CMakeFiles/help_menu.dir/gui/actions/help.c.o.d -o src/CMakeFiles/help_menu.dir/gui/actions/help.c.o -c /home/Source/ansel/src/gui/actions/help.c
<command-line>: error: macro names must be identifiers
[44/930] Building CXX object src/exter...polators.dir/Cr2sRawInterpolator.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by aurelienpierre** [comment]
What version of GCC ? We support GCC >= 12.

**Comment by Markfas** [comment]
It is gcc 12.3.0

**Comment by aurelienpierre** [comment]
Well, I don't know what to do here. 

1. The CI build passes on Ubuntu 24.04 with GCC 12 and 14 : https://github.com/aurelienpierreeng/ansel/actions/runs/24957324087
2. your compilation error doesn't show the precise file/line that makes it fail, which is quite unusual,
3. that particular error `macro names must be identifiers` happens when using digits into macro names, which we don't do.

So that makes no sense.

**Comment by Markfas** [comment]
Sorry that I cannot provide more infomation. Is there a way I can set a debug-flag or something to give you more details of the compilation error? The thing is, that it worked up to (including) commit `4ccef4d`
With `cffd508 CMake modernization: round 2` something broke the compilation. AppImage does not work on Ubuntu 22.04 - that's why I use to build myself.

**Comment by aurelienpierre** [comment]
you can try `sh build.sh --build-type Debug` but this option changes the amount of debug info we have at runtime, and your problem is at build time, so I doubt it will produce anything meaningful.

**Comment by aurelienpierre** [comment]
I had to downgrade AppImage nightly builds to GCC 12 on Ubuntu 22.04 and the build passed. That means the error is most likely on your system, which confirms the odd and cryptic error message from GCC, which is usually more verbose than that.

**Comment by blonchkman** [comment]
Hello,

I encountered a similar issue with gcc 12.2 on debian 12 (no GPU) after a clone and compilation on April 29th but was unable to report the incident until now. The logs also show a compilation error and a macro name error at steps [4/888] and [5/888].
I opened a new issue with the log of my last build attempt ( ec9ccce9 )

Kindest regards and thank you for this fantastic work.
